#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - hello@bard0.com

"""
JPEG-LS encoder simulation runner.

Usage:
    python run_sim.py                        # NEAR=0, default random bubbles, golden self-check
    python run_sim.py --near 0 1 2           # multiple NEAR values
    python run_sim.py --bubble 0 -1 1 3      # multiple BUBBLE_CONTROL values (full matrix)
    python run_sim.py --regen-golden         # force regenerate golden files
    python run_sim.py --no-check             # compress only, skip self-check

Goldens depend on NEAR only (bubbles change timing, not encoded bytes), so a single
golden set per NEAR is generated once and reused across all bubble values.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

SIM_DIR    = Path(__file__).parent.resolve()
RTL_FILE   = SIM_DIR / ".." / "RTL" / "jls_encoder.v"
TB_FILE    = SIM_DIR / "tb_jls_encoder.v"
SIM_OUT    = SIM_DIR / "sim.out"
GOLDEN_DIR = SIM_DIR / "golden"
CONFIG_VH  = SIM_DIR / "sim_config.vh"

# Common Windows install locations for iverilog
_IVERILOG_SEARCH = [
    r"C:\iverilog\bin",
    r"C:\Program Files\iverilog\bin",
    r"C:\msys64\mingw64\bin",
    r"C:\msys64\usr\bin",
]

_IVERILOG = None
_VVP      = None


def _find_tool(name):
    """Return the full Path to a tool, searching PATH then known locations."""
    for p in os.environ.get("PATH", "").split(os.pathsep):
        for suffix in ("", ".exe"):
            c = Path(p) / (name + suffix)
            if c.exists():
                return c
    for loc in _IVERILOG_SEARCH:
        for suffix in ("", ".exe"):
            c = Path(loc) / (name + suffix)
            if c.exists():
                print(f"[INFO] Found {name} at {c}", flush=True)
                return c
    raise FileNotFoundError(
        f"{name} not found. Install iverilog or add its bin directory to PATH.\n"
        "  Download: https://bleyer.org/icarus/"
    )


def _ensure_tools():
    global _IVERILOG, _VVP
    if _IVERILOG is None:
        _IVERILOG = _find_tool("iverilog")
        _VVP      = _find_tool("vvp")


def write_config(near, bubble, mode, golden_dir):
    """Write sim_config.vh so the testbench picks up the right settings."""
    lines = [
        "// Auto-generated by run_sim.py — do not edit by hand",
        f"`define NEAR           {near}",
        f"`define BUBBLE_CONTROL ({bubble})",
        f'`define GOLDEN_JLS_DIR "{golden_dir.as_posix()}"',
    ]
    if mode == "generate":
        lines.append("`define GENERATE_GOLDEN")
    elif mode == "check":
        lines.append("`define SELF_CHECK")
    CONFIG_VH.write_text("\n".join(lines) + "\n")


def run_iverilog():
    """Compile TB + RTL. Returns True on success."""
    _ensure_tools()
    cmd = [
        str(_IVERILOG), "-g2001",
        "-o", str(SIM_OUT),
        "-D", "HAVE_SIM_CONFIG",
        str(TB_FILE),
        str(RTL_FILE),
    ]
    print(f"\n[COMPILE] {' '.join(cmd)}", flush=True)
    print("-" * 60, flush=True)
    rc = subprocess.run(cmd, cwd=SIM_DIR).returncode
    print("-" * 60, flush=True)
    return rc == 0


def run_vvp():
    """Run the compiled simulation. Returns True on success (exit 0)."""
    _ensure_tools()
    cmd = [str(_VVP), "-n", str(SIM_OUT)]
    print(f"\n[SIM] {' '.join(cmd)}", flush=True)
    print("-" * 60, flush=True)
    rc = subprocess.run(cmd, cwd=SIM_DIR).returncode
    print("-" * 60, flush=True)
    return rc == 0


def golden_dir_for(near):
    return GOLDEN_DIR / f"near{near}"


def golden_exists(near):
    d = golden_dir_for(near)
    return d.is_dir() and any(d.glob("*.jls"))


def generate_golden(near, bubble):
    """Generate golden .jls reference files for the given NEAR value."""
    gdir = golden_dir_for(near)
    gdir.mkdir(parents=True, exist_ok=True)

    print(f"\n>>> Generating golden files  NEAR={near}  ->  {gdir}", flush=True)
    write_config(near, bubble, mode="generate", golden_dir=gdir)

    if not run_iverilog():
        print("ERROR: compilation failed", flush=True)
        return False
    if not run_vvp():
        print("ERROR: simulation failed during golden generation", flush=True)
        return False

    files = list(gdir.glob("*.jls"))
    print(f"  Generated {len(files)} golden .jls files in {gdir}", flush=True)
    return len(files) > 0


def self_check(near, bubble):
    """Run self-check comparing output against golden files."""
    gdir = golden_dir_for(near)
    print(f"\n>>> Running self-check  NEAR={near}  against  {gdir}", flush=True)
    write_config(near, bubble, mode="check", golden_dir=gdir)

    if not run_iverilog():
        print("ERROR: compilation failed", flush=True)
        return False
    return run_vvp()


def compress_only(near, bubble):
    """Compress images with no self-check."""
    print(f"\n>>> Compressing  NEAR={near}  (no self-check)", flush=True)
    write_config(near, bubble, mode="compress", golden_dir=GOLDEN_DIR)

    if not run_iverilog():
        print("ERROR: compilation failed", flush=True)
        return False
    return run_vvp()


def main():
    parser = argparse.ArgumentParser(description="JPEG-LS encoder simulation runner")
    parser.add_argument(
        "--near", type=int, nargs="+", default=[0], metavar="N",
        help="NEAR value(s) 0-7 to test (default: 0)",
    )
    parser.add_argument(
        "--bubble", type=int, nargs="+", default=[-1], metavar="B",
        help="BUBBLE_CONTROL value(s) (default: -1 = random bubbles). "
             "Multiple values run the full (near × bubble) matrix.",
    )
    parser.add_argument(
        "--regen-golden", action="store_true",
        help="Force regeneration of golden reference files before checking",
    )
    parser.add_argument(
        "--no-check", action="store_true",
        help="Compress only, no self-check",
    )
    args = parser.parse_args()

    for n in args.near:
        if not 0 <= n <= 7:
            print(f"ERROR: NEAR={n} is out of range [0, 7]")
            sys.exit(1)

    overall_pass = True
    results = []  # list of (near, bubble, status)

    # Goldens depend only on NEAR, not on bubble timing. Generate once per NEAR using
    # the first bubble value, then reuse across all bubble values in the matrix.
    golden_bubble = args.bubble[0]

    for near in args.near:
        print(f"\n{'='*60}", flush=True)
        print(f"  NEAR = {near}", flush=True)
        print(f"{'='*60}", flush=True)

        if not args.no_check:
            if args.regen_golden or not golden_exists(near):
                ok = generate_golden(near, golden_bubble)
                if not ok:
                    print(f"ERROR: golden generation failed for NEAR={near}", flush=True)
                    overall_pass = False
                    for b in args.bubble:
                        results.append((near, b, "SKIP (no golden)"))
                    continue

        for bubble in args.bubble:
            print(f"\n--- NEAR={near}  BUBBLE={bubble} ---", flush=True)
            if args.no_check:
                ok = compress_only(near, bubble)
            else:
                ok = self_check(near, bubble)
            results.append((near, bubble, "PASS" if ok else "FAIL"))
            if not ok:
                overall_pass = False

    # Cleanup
    if SIM_OUT.exists():
        SIM_OUT.unlink()
    if CONFIG_VH.exists():
        CONFIG_VH.unlink()

    print(f"\n{'='*60}", flush=True)
    print("  REGRESSION MATRIX SUMMARY", flush=True)
    print(f"{'='*60}", flush=True)
    for near, bubble, status in results:
        print(f"  NEAR={near}  BUBBLE={bubble:>3}  ->  {status}", flush=True)
    print(f"{'='*60}", flush=True)
    if overall_pass:
        print("  RESULT: ALL PASSED", flush=True)
    else:
        print("  RESULT: FAILED", flush=True)
    print(f"{'='*60}\n", flush=True)

    sys.exit(0 if overall_pass else 1)


if __name__ == "__main__":
    main()
