
//--------------------------------------------------------------------------------------------------------
// Module  : tb_jls_encoder
// Type    : simulation, top
// Standard: Verilog 2001 (IEEE1364-2001)
// Function: testbench for jls_encoder,
//           load some .pgm files (uncompressed image file), and push them to jls_encoder.
//           get output JPEG-LS stream from jls_encoder, and write them to .jls files (JPEG-LS image file)
//
// Modes (pass via iverilog -D flag, e.g. -D SELF_CHECK):
//   default         : compress images, write .jls to OUTPUT_JLS_DIR
//   -D GENERATE_GOLDEN : compress images, write .jls to GOLDEN_JLS_DIR
//   -D SELF_CHECK      : compress images AND byte-compare against GOLDEN_JLS_DIR
//
// Overridable defines (pass via iverilog -D, e.g. -D NEAR=1):
//   NEAR            : 0~7 (default 0)
//   FILE_NO_FIRST   : first file number (default 1)
//   FILE_NO_FINAL   : last file number (default 22)
//   BUBBLE_CONTROL  : bubble insertion control (default -1)
//--------------------------------------------------------------------------------------------------------

`timescale 1ps/1ps

// sim_config.vh is generated by run_sim.py before each compile.
// It defines: NEAR, BUBBLE_CONTROL, GOLDEN_JLS_DIR, and one of GENERATE_GOLDEN / SELF_CHECK.
// If running manually without run_sim.py, create sim_config.vh yourself or use the defaults below.
`ifdef HAVE_SIM_CONFIG
`include "sim_config.vh"
`endif

`ifndef NEAR
`define NEAR            0
`endif
`ifndef BUBBLE_CONTROL
`define BUBBLE_CONTROL  (-1)
`endif
`ifndef GOLDEN_JLS_DIR
`define GOLDEN_JLS_DIR  "./golden"
`endif

`define FILE_NO_FIRST   1
`define FILE_NO_FINAL   22
`define FILE_NAME_FORMAT  "test%03d"
`define INPUT_PGM_DIR     "./images"
`define OUTPUT_JLS_DIR    "."


module tb_jls_encoder ();

//initial $dumpvars(1, tb_jls_encoder);

// -------------------------------------------------------------------------------------------------------------------
//   generate clock and reset
// -------------------------------------------------------------------------------------------------------------------
reg          rstn = 1'b0;
reg           clk = 1'b0;
always #50000 clk = ~clk;  // 10MHz
initial begin repeat(4) @(posedge clk); rstn<=1'b1; end


// -------------------------------------------------------------------------------------------------------------------
//   heartbeat: one minimal line every HEARTBEAT_CYCLES clocks so the outer harness
//   can confirm the simulation is alive without polluting or slowing the run.
// -------------------------------------------------------------------------------------------------------------------
`ifndef HEARTBEAT_CYCLES
`define HEARTBEAT_CYCLES 2000000
`endif
integer hb_cnt = 0;
always @(posedge clk) begin
    hb_cnt <= hb_cnt + 1;
    if(hb_cnt >= `HEARTBEAT_CYCLES) begin
        hb_cnt <= 0;
        $display("  [alive] t=%0t", $time);
    end
end


// -------------------------------------------------------------------------------------------------------------------
//   Optional debug trace: with -D DUMP_EX the testbench writes a per-cycle log of
//   key pipeline signals to ex_trace.txt. Useful for cycle-accurate pre/post-RTL
//   diffs when investigating encoder regressions. No effect when DUMP_EX is unset.
// -------------------------------------------------------------------------------------------------------------------
`ifdef DUMP_EX
integer trace_fp = 0;
initial trace_fp = $fopen("./ex_trace.txt", "w");
always @(posedge clk)
    if(rstn && u_jls_encoder.o_e)
        $fwrite(trace_fp, "fno=%0d o_data=%04x o_last=%0d\n",
            file_no, u_jls_encoder.o_data, u_jls_encoder.o_last);
`endif


// -------------------------------------------------------------------------------------------------------------------
//   signals for jls_encoder module
// -------------------------------------------------------------------------------------------------------------------
reg        i_sof = 0;
reg [13:0] i_w   = 0;
reg [13:0] i_h   = 0;
reg        i_e   = 0;
reg [ 7:0] i_x   = 0;
wire       o_e;
wire       o_last;
wire[15:0] o_data;


reg [7:0] img [8192*8192-1:0];
integer w = 0, h = 0;

task load_img;
    input [256*8:1] fname;
    reg [256*8-1:0] line;
    integer linelen, depth, scanf_num, fp, i;
begin
    depth = 0;
    fp = $fopen(fname, "rb");
    if (fp==0) begin
        $display("*** error: could not open file %s", fname);
        $finish;
    end
    linelen = $fgets(line, fp);
    if (line[8*(linelen-2)+:16] != 16'h5035) begin
        $display("*** error: the first line must be P5");
        $fclose(fp);
        $finish;
    end
    scanf_num = $fgets(line, fp);
    scanf_num = $sscanf(line, "%d%d", w, h);
    if(scanf_num == 1) begin
        scanf_num = $fgets(line, fp);
        scanf_num = $sscanf(line, "%d", h);
    end
    scanf_num = $fgets(line, fp);
    scanf_num = $sscanf(line, "%d", depth);
    if (depth!=255) begin
        $display("*** error: images depth must be 255");
        $fclose(fp);
        $finish;
    end
    for (i=0; i<h*w; i=i+1)
        img[i] = $fgetc(fp);
    $fclose(fp);
end
endtask


// -------------------------------------------------------------------------------------------------------------------
//   task: feed image pixels to jls_encoder module
// -------------------------------------------------------------------------------------------------------------------
task feed_img;
    input integer bubble_control;
    integer       num_bubble, i;
begin
    repeat(368) begin
        @(posedge clk)
        i_sof <= 1'b1;
        i_w   <= w - 1;
        i_h   <= h - 1;
        {i_e, i_x} <= 0;
    end

    for(i=0; i<h*w; i=i+1) begin
        if(bubble_control<0) begin
            num_bubble = $random % (1-bubble_control);
            if(num_bubble<0) num_bubble = -num_bubble;
        end else begin
            num_bubble = bubble_control;
        end
        repeat(num_bubble) @(posedge clk) {i_sof, i_w, i_h, i_e, i_x} <= 0;
        @(posedge clk)
        {i_sof, i_w, i_h} <= 0;
        i_e <= 1'b1;
        i_x <= img[i];
    end

    repeat(32) @(posedge clk) {i_sof, i_w, i_h, i_e, i_x} <= 0;
end
endtask


// -------------------------------------------------------------------------------------------------------------------
//   jls_encoder instance
// -------------------------------------------------------------------------------------------------------------------
jls_encoder #(
    .NEAR ( `NEAR )
) u_jls_encoder (
    .rstn   ( rstn   ),
    .clk    ( clk    ),
    .i_sof  ( i_sof  ),
    .i_w    ( i_w    ),
    .i_h    ( i_h    ),
    .i_e    ( i_e    ),
    .i_x    ( i_x    ),
    .o_e    ( o_e    ),
    .o_last ( o_last ),
    .o_data ( o_data )
);


// -------------------------------------------------------------------------------------------------------------------
//   drive inputs: load and feed all images
// -------------------------------------------------------------------------------------------------------------------
integer file_no;
reg [256*8:1] input_file_name;
reg [256*8:1] input_file_format;

integer pass_count = 0;
integer fail_count = 0;
integer skip_count = 0;

initial begin
    $sformat(input_file_format, "%s/%s.pgm", `INPUT_PGM_DIR, `FILE_NAME_FORMAT);

    while(~rstn) @(posedge clk);

    for(file_no=`FILE_NO_FIRST; file_no<=`FILE_NO_FINAL; file_no=file_no+1) begin
        $sformat(input_file_name, input_file_format, file_no);
        load_img(input_file_name);
        $display("  loading %s (%dx%d)", input_file_name, w, h);
        if(w<5 || w>16384 || h<1 || h>16384)
            $display("    *** image size not supported, skipping ***");
        else
            feed_img(`BUBBLE_CONTROL);
    end

    repeat(200) @(posedge clk);

`ifdef SELF_CHECK
    $display("");
    $display("=== SELF-CHECK SUMMARY (NEAR=%0d) ===", `NEAR);
    $display("  PASS : %0d", pass_count);
    $display("  FAIL : %0d", fail_count);
    $display("  SKIP : %0d  (golden file missing)", skip_count);
    if(fail_count > 0)
        $fatal(1, "*** SELF-CHECK FAILED ***");
    else if(pass_count == 0)
        $fatal(1, "*** SELF-CHECK FAILED: no golden files found in %s ***", `GOLDEN_JLS_DIR);
    else
        $display("*** ALL CHECKS PASSED ***");
`elsif GENERATE_GOLDEN
    $display("");
    $display("=== GOLDEN FILES WRITTEN to %s ===", `GOLDEN_JLS_DIR);
`endif

    $finish;
end


// -------------------------------------------------------------------------------------------------------------------
//   capture output stream: write to file, optionally compare against golden
// -------------------------------------------------------------------------------------------------------------------
`ifdef GENERATE_GOLDEN
reg [256*8:1] out_fmt;
initial $sformat(out_fmt, "%s/%s.jls", `GOLDEN_JLS_DIR, `FILE_NAME_FORMAT);
`else
reg [256*8:1] out_fmt;
initial $sformat(out_fmt, "%s/%s.jls", `OUTPUT_JLS_DIR, `FILE_NAME_FORMAT);
`endif

reg [256*8:1] out_name;
integer       out_fp  = 0;
integer       opened  = 0;

`ifdef SELF_CHECK
reg [256*8:1] gold_fmt;
initial $sformat(gold_fmt, "%s/%s.jls", `GOLDEN_JLS_DIR, `FILE_NAME_FORMAT);
reg [256*8:1] gold_name;
integer       gold_fp      = 0;
integer       mismatch_cnt = 0;
integer       byte_offset  = 0;
integer       gb0, gb1;
`endif

always @(posedge clk)
    if(o_e) begin

        // open output file on first byte of an image
        if(opened == 0) begin
            opened = 1;
            $sformat(out_name, out_fmt, file_no);
            out_fp = $fopen(out_name, "wb");
            `ifdef SELF_CHECK
            mismatch_cnt = 0;
            byte_offset  = 0;
            $sformat(gold_name, gold_fmt, file_no);
            gold_fp = $fopen(gold_name, "rb");
            if(gold_fp == 0)
                $display("  [SKIP] golden not found: %s", gold_name);
            `endif
        end

        // write compressed bytes
        if(out_fp != 0)
            $fwrite(out_fp, "%c%c", o_data[7:0], o_data[15:8]);

        // byte-compare against golden
        `ifdef SELF_CHECK
        if(gold_fp != 0) begin
            gb0 = $fgetc(gold_fp);
            if(gb0 !== o_data[7:0]) begin
                if(mismatch_cnt == 0)
                    $display("  [MISMATCH] byte %0d: got 0x%02X expected 0x%02X",
                             byte_offset, o_data[7:0], gb0);
                mismatch_cnt = mismatch_cnt + 1;
            end
            gb1 = $fgetc(gold_fp);
            if(gb1 !== o_data[15:8]) begin
                if(mismatch_cnt == 0)
                    $display("  [MISMATCH] byte %0d: got 0x%02X expected 0x%02X",
                             byte_offset+1, o_data[15:8], gb1);
                mismatch_cnt = mismatch_cnt + 1;
            end
            byte_offset = byte_offset + 2;
        end
        `endif

        // close and report at end of each image
        if(o_last) begin
            opened = 0;
            if(out_fp != 0) $fclose(out_fp);
            `ifdef SELF_CHECK
            if(gold_fp != 0) begin
                $fclose(gold_fp);
                if(mismatch_cnt == 0) begin
                    $display("  [PASS] %s  (%0d bytes)", out_name, byte_offset);
                    pass_count = pass_count + 1;
                end else begin
                    $display("  [FAIL] %s  (%0d mismatches in %0d bytes)",
                             out_name, mismatch_cnt, byte_offset);
                    fail_count = fail_count + 1;
                end
            end else begin
                skip_count = skip_count + 1;
            end
            `endif
        end

    end

endmodule
